In [1]:
import numpy as np

In [2]:
x = [[1], [2], [3]]

In [4]:
x

[[1], [2], [3]]

In [6]:
np.squeeze(x)

array([1, 2, 3])

In [7]:
np.squeeze(x).shape

(3,)

In [8]:
x2 = np.squeeze(x)

In [17]:
x2 = [[0, 3, 3, 3, 3, 3, 0, 0, 0, 0],
       [5, 3, 3, 3, 0, 0, 0, 0, 9, 9],
       [5, 3, 3, 9, 0, 0, 0, 9, 9, 9],
       [0, 9, 0, 0, 0, 0, 9, 9, 9, 9],
       [9, 9, 9, 0, 0, 9, 9, 9, 9, 9],
       [4, 9, 0, 0, 9, 9, 9, 9, 9, 9]]

In [19]:
np.squeeze(x2).shape

(6, 10)

In [20]:
np.squeeze(x2)

array([[0, 3, 3, 3, 3, 3, 0, 0, 0, 0],
       [5, 3, 3, 3, 0, 0, 0, 0, 9, 9],
       [5, 3, 3, 9, 0, 0, 0, 9, 9, 9],
       [0, 9, 0, 0, 0, 0, 9, 9, 9, 9],
       [9, 9, 9, 0, 0, 9, 9, 9, 9, 9],
       [4, 9, 0, 0, 9, 9, 9, 9, 9, 9]])

In [21]:
x2

[[0, 3, 3, 3, 3, 3, 0, 0, 0, 0],
 [5, 3, 3, 3, 0, 0, 0, 0, 9, 9],
 [5, 3, 3, 9, 0, 0, 0, 9, 9, 9],
 [0, 9, 0, 0, 0, 0, 9, 9, 9, 9],
 [9, 9, 9, 0, 0, 9, 9, 9, 9, 9],
 [4, 9, 0, 0, 9, 9, 9, 9, 9, 9]]

In [22]:
x2.shape

AttributeError: 'list' object has no attribute 'shape'

In [11]:
import tensorflow as tf

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [12]:
tf.shape(x)

<tf.Tensor 'Shape:0' shape=(2,) dtype=int32>

In [13]:
sess = tf.Session()

In [14]:
sess.run(tf.shape(x))

array([3, 1])

In [23]:
sess.run(tf.shape(x2))

array([ 6, 10])

In [24]:
result = np.squeeze(x2)

In [26]:
sess.run(tf.shape(x2))

array([ 6, 10])