In [1]:
import tensorflow as tf

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
x = tf.constant([[[1.0, 2.0],[3.0, 4.0],[5.0, 6.0]],[[7.0, 8.0],[9.0, 10.0],[11.0, 12.0]]])

In [8]:
sess = tf.Session()

In [9]:
sess.run(x)

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]], dtype=float32)

In [16]:
sess.run(tf.shape(x))

array([2, 3, 2])

In [17]:
sess.run(tf.reduce_mean(x, axis=0))

array([[4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float32)

In [18]:
sess.run(tf.reduce_mean(x, axis=1))

array([[ 3.,  4.],
       [ 9., 10.]], dtype=float32)

In [19]:
sess.run(tf.reduce_mean(x, axis=2))

array([[ 1.5,  3.5,  5.5],
       [ 7.5,  9.5, 11.5]], dtype=float32)

In [20]:
sess.run(x)

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]], dtype=float32)

In [26]:
sess.run(tf.expand_dims(x, 1))

array([[[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]]],


       [[[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]]], dtype=float32)

In [27]:
sess.run(tf.shape(x))

array([2, 3, 2])

In [28]:
sess.run(x)

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]], dtype=float32)